export interface keyValueType {
  label: string,
  content: string
}

export const keyValueLists: keyValueType[][][] =
  [
    [
      [
        { label: 'q', content: 'p' },
        { label: 'w', content: 'o' },
        { label: 'e', content: 'i' },
        { label: 'r', content: 'u' },
        { label: 't', content: 'y' },
        { label: 'y', content: 't' },
        { label: 'u', content: 'r' },
        { label: 'i', content: 'e' },
        { label: 'o', content: 'w' },
        { label: 'p', content: 'q' }
      ],
      [
        { label: 'a', content: 'l' },
        { label: 's', content: 'k' },
        { label: 'd', content: 'j' },
        { label: 'f', content: 'h' },
        { label: 'g', content: 'g' },
        { label: 'h', content: 'f' },
        { label: 'j', content: 'd' },
        { label: 'k', content: 's' },
        { label: 'l', content: 'a' }
      ],
      [
        { label: 'z', content: 'm' },
        { label: 'x', content: 'n' },
        { label: 'c', content: 'b' },
        { label: 'v', content: 'v' },
        { label: 'b', content: 'c' },
        { label: 'n', content: 'x' },
        { label: 'm', content: 'z' }]
    ],
    [
      [
        { label: 'Q', content: 'P' },
        { label: 'W', content: 'O' },
        { label: 'E', content: 'I' },
        { label: 'R', content: 'U' },
        { label: 'T', content: 'Y' },
        { label: 'Y', content: 'T' },
        { label: 'U', content: 'R' },
        { label: 'I', content: 'E' },
        { label: 'O', content: 'W' },
        { label: 'P', content: 'Q' }
      ],
      [
        { label: 'A', content: 'L' },
        { label: 'S', content: 'K' },
        { label: 'D', content: 'J' },
        { label: 'F', content: 'H' },
        { label: 'G', content: 'G' },
        { label: 'H', content: 'F' },
        { label: 'J', content: 'D' },
        { label: 'K', content: 'S' },
        { label: 'L', content: 'A' }
      ],
      [
        { label: 'Z', content: 'M' },
        { label: 'X', content: 'N' },
        { label: 'C', content: 'B' },
        { label: 'V', content: 'V' },
        { label: 'B', content: 'C' },
        { label: 'N', content: 'X' },
        { label: 'M', content: 'Z' }
      ]
    ]
  ]