export interface keyValueType {
  label: string,
  content: string
}

export const keyValueLists: keyValueType[][] = [
  [
    { label: 'q', content: 'p' },
    { label: 'w', content: 'o' },
    { label: 'e', content: 'i' },
    { label: 'r', content: 'u' },
    { label: 't', content: 'y' },
    { label: 'y', content: 't' },
    { label: 'u', content: 'r' },
    { label: 'i', content: 'e' },
    { label: 'o', content: 'w' },
    { label: 'p', content: 'q' }
  ],
  [
    { label: 'a', content: 'l' },
    { label: 's', content: 'k' },
    { label: 'd', content: 'j' },
    { label: 'f', content: 'h' },
    { label: 'g', content: 'g' },
    { label: 'h', content: 'f' },
    { label: 'j', content: 'd' },
    { label: 'k', content: 's' },
    { label: 'l', content: 'a' }
  ],
  [
    { label: 'z', content: 'm' },
    { label: 'x', content: 'n' },
    { label: 'c', content: 'b' },
    { label: 'v', content: 'v' },
    { label: 'b', content: 'c' },
    { label: 'n', content: 'x' },
    { label: 'm', content: 'z' }
  ]
]