export default class Constants {
  static readonly KEYBOARD_HEIGHT = 640
  static readonly KEY_WIDTH_PERCENT = '10%'
  static readonly KEY_HEIGHT_PERCENT = '25%'
  static readonly KEY_SHIFT_WIDTH_PERCENT = '15%'
  static readonly KEY_SPACE_WIDTH_PERCENT = '50%'
  static readonly KEY_BACKSPACE_WIDTH_PERCENT = '20%'
  static readonly KEY_HIDE_WIDTH_PERCENT = '15%'
  static readonly FULL_PERCENT = '100%'
  static readonly SPACE_BETWEEN_ELEMENTS = 12
}